<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>313b34db-f412-4570-a9df-1a7bdea20aaa</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
		<PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.3" />
		<PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.8.0-preview.260528.1" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.8.0" />
		<PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.8.0" />
		<PackageReference Include="Microsoft.Agents.AI.A2A" Version="1.8.0-preview.260528.1" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.6.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
		<PackageReference Include="ObjectDumper.NET" Version="4.3.2" />
		<PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
	</ItemGroup>
</Project>
