<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.3.0" />
		<PackageReference Include="MartinCostello.Logging.XUnit.v3" Version="0.7.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Mediator.SourceGenerator" Version="3.0.1" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Test.Application\Test.Application.csproj" />
		<ProjectReference Include="..\Test.Infrastructure\Test.Infrastructure.csproj" />
		<ProjectReference Include="..\Test.Domain\Test.Domain.csproj" />
	</ItemGroup>

</Project>
