schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Mutation {
  addComment(input: AddCommentInput!): AddCommentPayload!
  createUser(input: CreateUserInput!): CreateUserPayload!
}

type Query {
  books: [Book!]!
  author(id: Int!): Author!
  hello: String!
  newsCountries: [NewsCountry!]!
  "Get Geo Coordinates for a given location."
  geoCoordinates(location: String!): Response8!
}

type Subscription {
  itemUpdated: Item!
  itemPublished(author: String!): Item!
  dataAdded: Item!
}

type UserNameTakenError implements UserError {
  code: String!
  message: String!
}

interface UserError {
  message: String!
  code: String!
}

type Author {
  name: String!
}

type Book {
  title: String!
  author: Author!
}

input AddCommentInput {
  articleId: ID!
  text: String!
}

type AddCommentPayload {
  "Similar to HTTP status code, represents the status of the mutation."
  code: Int!
  "Indicates whether the mutation was successful."
  success: Boolean!
  "Human-readable message for the UI."
  message: String!
  comment: Comment
}

type NewsCountry {
  newsArticles: [NewsArticle!]!
  code: String!
  name: String!
  id: ID!
}

type Response8 {
  latitude: Float!
  longitude: Float!
  city: String
  additionalProperties: [KeyValuePairOfStringAndObject!]
}

type Item {
  name: String!
}

type KeyValuePairOfStringAndObject {
  key: String!
}

type NewsArticle {
  comments: [Comment!]!
  title: String!
  content: String!
  id: ID!
}

type Comment {
  text: String!
  id: ID!
}

input CreateUserInput {
  username: ID!
}

union CreateUserError = UserNameTakenError

type CreateUserPayload {
  book: Book
  errors: [CreateUserError!]
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost("The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc." weight: String!) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION